### ISSUE TITLE
grails 2.4.4 asset pipeline vs resources plugin

### ISSUE THREAD

**Issue by bahmed73** [bobbywarner/grails-stripe#9]
Hello:

I am having issues with the stripe plugin for grails 2.4.4. 

https://grails.org/plugin/stripe

In my BuildConfig.groovy,
compile ":jquery-ui:1.10.4"
compile ":stripe:2.8"

I am not using a resources plugin, rather asset pipeline plugin. When I start my grails application, I am getting all sorts of errors. This is because all the paths to relative images, css and js are messed up. The stripe plugin is forcing the usage of resources plugin. 

| Error 2015-04-08 11:27:59,253 [localhost-startStop-1] ERROR resource.ResourceMeta  - Resource not found: /assets/auth.css
| Error 2015-04-08 11:27:59,278 [localhost-startStop-1] ERROR resource.ResourceMeta  - Resource not found: /assets/spring-security-ui.js
| Error 2015-04-08 11:27:59,302 [localhost-startStop-1] ERROR resource.ResourceMeta  - Resource not found: /assets/ajaxLogin.js
| Error 2015-04-08 11:27:59,323 [localhost-startStop-1] ERROR resource.ResourceMeta  - Resource not found: /assets/stripe-v2.js     

Any help will be greatly appreciated.

Thanks,
Bilal

**Comment by MiguelAngel82** [comment]
Hello.

I'm having the same problem with Grails 2.4.4 and stripe 2.8. When the application is run, this message is shown:

| Error 2016-04-04 11:02:02,441 [localhost-startStop-1] ERROR resource.ResourceMeta  - Resource not found: /assets/stripe-v2.js

Have you fixed this? Or anybody has a solution for this?

Thank you very much,
Miguel.

**Comment by bobbywarner** [comment]
The plugin now uses Asset Pipeline
